# Generated by Django 2.0.5 on 2018-05-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyrates',
            old_name='updaated',
            new_name='updated',
        ),
    ]
